import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-10 space-y-6">
          <h1 className="text-lg">
            Nextjs changing pages not being cached bug
          </h1>
          <p>This bug has been killing me.</p>
          <p>
            <strong>Expected Results:</strong> There are two pages. There should
            be a very quick loading of fetching data when going between these
            pages. Nextjs then caches that data so changing pages afterwards
            will be instant. You can insect the browser and see that network
            loads the first time, but will load nothing afterwards.{" "}
          </p>
          <p>
            <strong>Bug:</strong> If you tab out of this website for a bit and
            then come back, the site will fetch from the server and load EVERY
            SINGLE TIME. You can see this in inspect performance.{" "}
          </p>
          <a
            href="https://github.com/BiigFish/next-page-changing-bug"
            className="text-blue-400"
          >
            Repo here
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
